### ISSUE TITLE
Nuxt warning about accessing deprecated compatibility layer - public runtime config

### ISSUE THREAD

**Issue by Ansis100** [nuxt-modules/strapi#340] opened 2023-04-19 19:57 UTC
I'm using the `useStrapiMedia` composable to render images from Strapi. This composable needs to read the Strapi URL from the public runtime config, however, Nuxt warns against doing it as it is currently implemented:

```[nuxt] [runtimeConfig] You are trying to access a public runtime config value (`strapi`) directly from the top level. This currently works (for backward compatibility with Nuxt 2) but this compatibility layer will be removed in v3.5. Instead, you can update `config['strapi']` to `config.public['strapi']`.```

My config is just:
```javascript
strapi: {
    url: "http://127.0.0.1:1337",
},
```

Is this cause for concern? Or does it just need a small fix and that's it?

**Comment by bayramorhan** [comment] 2023-04-20 01:13
yes . defining the strapi config causing the error. moving this into the runtimeConfig.public is alo didnt fix

**Comment by benjamincanac** [comment] 2023-04-20 09:38
The warning was caused by this breaking fix in https://github.com/nuxt/nuxt/releases/tag/v3.4.0: https://github.com/nuxt/nuxt/pull/20082

This should be fixed in latest v1.9.1 😊

**Closed** 2023-11-29 10:45 UTC
Labels: question
